name: iso_3166_1
description: >-
  An implementation of ISO_3166_1 in a similar way to an enum, 
  group by id, name, alpha2 and alpha3. 
  It provides id, alpha2, alpha3, flag and prefix number info
version: 2.0.0
# repository: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0     
dependencies:
  args: ^2.2.0
  characters: ^1.1.0
  tabular: ^0.6.3
  csv: ^5.0.0
  pretty_json: ^2.0.0
executables:
  list_countries:
